---
title: "Linking Health Outcomes to Refinery Emissions in the Bay Area"
author: "Niklas Lollo"
output: html_document
---

```{r setup, include=FALSE, echo=F}
knitr::opts_chunk$set(echo = TRUE)
# List of R packages
required_pkg <- c("tidyverse","maptools", "rgdal", "spatstat", "ggmap")
#pkgs_not_installed <- required_pkg[!sapply(required_pkg, function(p) require(p, character.only=T))]
#install.packages(pkgs_not_installed, dependencies=TRUE)

# Load all libraries at once.
lapply(required_pkg, library, character.only = TRUE) 
```

```{r time dataset, message=F, warning=F, echo=F}
# Inputs here are date_begin and date_end
timeframe <- function(date_begin = "2016-05-09 14:00", date_end = "2016-08-11 0:00"){
  exp_begin = as.POSIXct(date_begin, tz="GMT", format="%Y-%m-%d %H")
  exp_end = as.POSIXct(date_end, tz="GMT", format="%Y-%m-%d %H")
  out = data_frame(day = seq(exp_begin, exp_end, by = 3600))
  return(out)
}
full_time <- timeframe()
# Manual
date_begin = "2016-05-09 14:00"
date_end = "2016-08-11 0:00"
exp_begin = as.POSIXct(date_begin, tz="GMT", format="%Y-%m-%d %H")
exp_end = as.POSIXct(date_end, tz="GMT", format="%Y-%m-%d %H")
```

```{r load air quality data, warning=F, message=F, echo=F}
# load air quality data
feed_4902 <- read_csv("../refinery_data/airQuality_feed4902_data.csv")
feed_4901 <- read_csv("../refinery_data/airQuality_feed4901_data.csv")
feed_4902_methane <- read_csv("../refinery_data/airQuality_N20_methane_4902_data.csv")

# Make hourly averages
## Set zero's to NA to not "mess up" average
feed_4902[feed_4902 == 0] <- NA
## Create new dataframe
hourly_4902 <- feed_4902 %>%
  # Select the day and hour of interest (get rid of minute and seconds)
  group_by(
    # Creates new variables
    day = as.POSIXct(cut(t, breaks='hour'))) %>%
  summarise(
    # Averages
    sulfur_dioxide = mean(sulfurDioxide, na.rm=T),
    carbon_monoxide = mean(carbonMonoxide, na.rm=T),
    ozone = mean(ozone, na.rm=T)) %>%
  ungroup() %>%
  # Arrange the columns by day
  arrange(day) %>%
  full_join(full_time, by = "day")

# Do the same for the other feed4902 dataframe
feed_4902_methane[feed_4902_methane == 0] <- NA
hourly_4902_methane <- feed_4902_methane %>%
    group_by(
    # Creates new variables
    day = as.POSIXct(cut(t, breaks='hour'))) %>%
  summarise(
    # Averages
    methane = mean(Methane, na.rm=T),
    benzene = mean(Benzene, na.rm=T),
    nitrous_oxide = mean(`Nitrous Oxide`, na.rm=T)) %>%
  # Arrange the columns by day
  arrange(day) %>%
  full_join(full_time, by = "day")

air_qual_4902 <- right_join(hourly_4902, hourly_4902_methane, by = "day") %>%
  mutate(id = "feed_4902")

# Do the same for feed 4901
feed_4901[feed_4901 == 0] <- NA
air_qual_4901 <- feed_4901 %>%
  # Select the day and hour of interest (get rid of minute and seconds)
  group_by(
    # Creates new variables
    day = as.POSIXct(cut(t, breaks='hour'))) %>%
    # Averages
  summarise(
    sulfur_dioxide = mean(sulfurDioxide, na.rm=T),
    carbon_monoxide = mean(carbonMonoxide, na.rm=T),
    ozone = mean(ozone, na.rm=T)) %>%
  mutate(
    id = "feed_4901"
  ) %>%
  # Arrange the columns by day
  arrange(day) %>%
  full_join(full_time, by = "day")

# Remove intermediate dataframes
rm(hourly_4902, hourly_4902_methane)
# Remove original dataframes
rm(feed_4901, feed_4902,feed_4902_methane)
```

```{r load paco data, warning=F, message=F, echo=F}
# load paco data
paco <- read_csv("../refinery_data/paco_all.csv")

# Creating new dataframe
paco <- paco %>%
  mutate(
    # Remove extra values (supposed to be a correction)
    when=gsub("\\+0000","",when),
    # Converting / to - part 1
    when=sub("[[:punct:]]","-",when),
    # Converting / to - part 2
    when=sub("\\/","-",when),
    # Rename persons of interest
    who = replace(who, who=="meaningfrommonitoring3@gmail.com", "m3"),
    who = replace(who, who=="meaningfrommonitoring5@gmail.com", "m5"),
    who = replace(who, who=="meaningfrommonitoring7@gmail.com", "m7"),
    who = replace(who, who=="meaningfrommonitoring9@gmail.com", "m9"),
    who = replace(who, who=="meaningfrommonitoring10@gmail.com", "m10"),
    who = replace(who, who=="meaningfrommonitoring11@gmail.com", "m11"),
    who = replace(who, who=="meaningfrommonitoring16@gmail.com", "m16")
  ) %>%
  mutate(
    # Make person column as a factor
    id = as.factor(who),
    # Convert date column to datetime
    t = as.POSIXct(when, tz="GMT", format="%Y-%m-%d %H:%M:%S")) %>%
  # Remove columns not of interest
  select(-c(who, when, appId, pacoVersion, experimentId,
            experimentName, experimentVersion, experimentGroupName,
            actionTriggerId, actionId, actionSpecId, responseTime,
            scheduledTime, timeZone)) %>%
  # Select persons of interest 
  filter(id == "m3" | id == "m5" | id == "m7" |
      id == "m9" | id == "m10" | id == "m11" |
      id == "m16") %>%
  arrange(t)

# Remove incorrect values
paco$SPO2[paco$SPO2 == 0 | paco$SPO2 > 100 | paco$SPO2 < 80] <- NA
# Make hourly dataframe
paco_hourly <- paco %>%
  # Select the person, day and hour of interest
  group_by(id,
    # Creates new variables
    day = as.POSIXct(cut(t, breaks='hour'))) %>%
  # Average
  summarise(blood_oxygen = mean(SPO2, na.rm=T)) %>%
  filter(is.na(blood_oxygen) == F) %>% 
  complete(expand(nesting(id), day = seq(exp_begin, exp_end, by = 3600)),  
           #completing all levels of id:day
              fill = list(blood_oxygen = NA)) %>%
  # Select persons of interest 
  filter(id == "m3" | id == "m5" | id == "m7" |
      id == "m9" | id == "m10" | id == "m11" |
      id == "m16") %>%
  # Arrange the columns by person
  arrange(id)

rm(paco)
```

```{r load fitbit data, message=F, warning=F, echo=F}
# Load fitbit data
fb_body <- read_csv("../refinery_data/fitbit_body_data.csv")
fb_activities <- read_csv("../refinery_data/fitbit_activities_data.csv")
fb_sleep <- read_csv("../refinery_data/fitbit_sleep_data.csv")

# Merge daily fitbit data
fb_daily <- inner_join(fb_body, fb_activities, fb_sleep, by = "t")
rm(fb_body, fb_activities, fb_sleep)

# Load intraday activity
fb_intraday_m3 <- read_csv("../refinery_data/fitbit_intradayactivities_m3.csv") %>%
  mutate(id = "m3")
fb_intraday_m5 <- read_csv("../refinery_data/fitbit_intradayactivities_m5.csv")%>%
  mutate(id = "m5")
fb_intraday_m7 <- read_csv("../refinery_data/fitbit_intradayactivities_m7.csv")%>%
  mutate(id = "m7")
fb_intraday_m9 <- read_csv("../refinery_data/fitbit_intradayactivities_m9.csv")%>%
  mutate(id = "m9")
fb_intraday_m11 <- read_csv("../refinery_data/fitbit_intradayactivities_m11.csv")%>%
  mutate(id = "m11")
fb_intraday_m16 <- read_csv("../refinery_data/fitbit_intradayactivities_m16.csv")%>%
  mutate(id = "m16")

# Combine dataframes
fb_intra <- bind_rows(fb_intraday_m3, fb_intraday_m5, .id = NULL) %>%
  bind_rows(fb_intraday_m7, .id = NULL) %>%
  bind_rows(fb_intraday_m9, .id = NULL) %>%
  bind_rows(fb_intraday_m11, .id = NULL) %>%
  bind_rows(fb_intraday_m16, .id = NULL) %>%
  mutate(id = as.factor(id))

# Remove intermediate columns
rm(fb_intraday_m3, fb_intraday_m5, fb_intraday_m7,
   fb_intraday_m9, fb_intraday_m11, fb_intraday_m16)

# Make hourly data
fb_intraday <- fb_intra %>% 
  group_by(id,
    # Creates new variables
    day = as.POSIXct(cut(t, breaks='hour'))) %>%
  summarise(
    # Averages
    calories = sum(calories, na.rm=T),
    distance = sum(distance, na.rm=T),
    steps = sum(steps, na.rm=T),
    heart_rate = mean(heart, na.rm=T),
    floors = sum(floors, na.rm=T),
    elevation = sum(elevation, na.rm=T)) %>%
    complete(expand(nesting(id), day = seq(exp_begin, exp_end, by = 3600)),  
         #completing all levels of id:day
              fill = list(calories = NA,distance = NA,
                          steps = NA, heart_rate = NA,
                          floors = NA, elevation = NA)) %>%
  # Select persons of interest 
  filter(id == "m3" | id == "m5" | id == "m7" |
      id == "m9" | id == "m10" | id == "m11" |
      id == "m16") %>%
  # Arrange the columns by day
  arrange(id, day)

# Remove original dataframes
rm(fb_intra, fb_daily)
```

```{r make individual data, message=F, warning=F, echo=F}
# Collect addresses
m3_locale = as.numeric(
  geocode("460 3rd St, Richmond, CA 94801",
          source="google"))
m5_locale = as.numeric(
  geocode("2515 Downer Ave, Richmond, CA 94804",
          source="google"))
m7_locale = as.numeric(
  geocode("2640 Esmond Ave, Richmond, CA 94804",
          source="google"))
m9_locale = as.numeric(
  geocode("1612 Mission Ave, San Pablo, CA 94806",
          source="google"))
m10_locale = as.numeric(
  geocode("1832 4th St, Richmond, CA 94801",
          source="google"))
m11_locale = as.numeric(
  geocode("2836 18th St, San Pablo, CA 94806",
          source="google"))
m16_locale = as.numeric(
  geocode("5733 Oakmont Dr, Richmond, CA 94806",
          source="google"))

# Make demographics dataframe
demographics <- data_frame(
  id =  c("m3","m5","m7","m9","m10","m11","m16"),
  age = c(21,34,45,33,56,67,51),
  sex = as.factor(c("male","female","male","female","female","male","female")),
  home_lat = c(m3_locale[2], m5_locale[2], m7_locale[2], 
          m9_locale[2], m10_locale[2], m11_locale[2], m16_locale[2]),
  home_long = c(m3_locale[1], m5_locale[1], m7_locale[1], 
           m9_locale[1], m10_locale[1], m11_locale[1], m16_locale[1]))

# Merge with fb_intraday
fb_data <- left_join(fb_intraday, demographics, by = "id") %>%
  ungroup %>%
  mutate(
    id = as.factor(id)
  )
paco_data <- full_join(paco_hourly, demographics, by = "id") %>%
  ungroup %>%
  mutate(
    id = as.factor(id)
    )

# Individual data
individual_data <- fb_data %>%
  bind_rows(paco_data, .id = NULL)

# Remove unnecessary dataframes
rm(paco_hourly, fb_intraday)
```

```{r create air quality dataset, message=F, warning=F, echo=F}
# Air Quality data
air_quality <- full_join(full_time, air_qual_4901, by = "day") %>%
  full_join(air_qual_4902, 
            by = c("day", "id", "sulfur_dioxide",
                   "carbon_monoxide", "ozone")) %>%
  select(day, id, everything()) %>%
  mutate(id = as.factor(id)) %>%
  arrange(day)
```

```{r moving window, message=F, warning=F, echo=F}
# Set hours of interest
hours = 5
# Moving window average of sulfur dioxide
air_quality <- 
  air_quality %>% 
  group_by(id) %>% 
  arrange(day) %>%
  mutate(sulfur_window = zoo::rollapply(sulfur_dioxide, 
                                        width = hours, #how many data to include
                                        FUN = mean, #function is mean
                                        na.rm = T, #avoids NA
                                        partial = T, #skips unnecessary datapoints
                                        align = "right")) %>%
  ungroup %>%
  arrange(id, day)
```

## Analysis
### Correlations
To read a correlation, visit this page: https://www.mathsisfun.com/data/images/correlation-examples.svg
```{r correlations, warning=F, message=F, echo=F}
# No filter function
correlation <- function(ind_data = individual_data, air_data = air_quality, 
                            var_1, var_2, var_time = day) {
    var_1 <- enquo(var_1)
    var_2 <- enquo(var_2)
    var_time <- enquo(var_time)

    ind_data %>%
      bind_rows(air_data, .id = NULL) %>%
      mutate(id = as.factor(id)) %>%
      select(!!var_1, !!var_2, !!var_time) %>%
      filter(!is.na(!!var_1) | !is.na(!!var_2))%>%
      group_by(!!var_time) %>%
      summarize(mean_var1 = mean(!!var_1, na.rm=T),
                mean_var2 = mean(!!var_2, na.rm=T)) %>% 
      ungroup %>%
      filter(!is.na(mean_var1) & !is.na(mean_var2)) %>%
      select(mean_var1, mean_var2) %>% 
      boot::corr() -> x
      x <- round(x, 3)
      y <- paste0("The correlation between ",var_1, " & ",var_2, " is ",x,".")
      cat(y[2])
}
# One filter function
# Note: this function only works for "==" not < or >
correlation_one_filter <- function(ind_data = individual_data, air_data = air_quality, 
                            var_1, var_2, var_time = day, filter_var_1, filter_1) {
    var_1 <- enquo(var_1)
    var_2 <- enquo(var_2)
    var_time <- enquo(var_time)
    filter_var_1 <- enquo(filter_var_1)

    ind_data %>%
      filter(UQ(filter_var_1) == filter_1) %>%
      bind_rows(air_data, .id = NULL) %>%
      mutate(id = as.factor(id)) %>%
      select(!!var_1, !!var_2, !!var_time) %>%
      filter(!is.na(!!var_1) | !is.na(!!var_2))%>%
      group_by(!!var_time) %>%
      summarize(mean_var1 = mean(!!var_1, na.rm=T),
                mean_var2 = mean(!!var_2, na.rm=T)) %>% 
      ungroup %>%
      filter(!is.na(mean_var1) & !is.na(mean_var2)) %>%
      select(mean_var1, mean_var2) %>% 
      boot::corr() -> x
      x <- round(x, 3)
      y <- paste0("The correlation between ",var_1, " & ",var_2, " is ",x, " among ",filter_1,"s.")
      cat(y[2])
}
# https://rpubs.com/hadley/dplyr-programming 
# See this for quosures and programming with dplyr

### Correlations ###
## Blood Oxygen and Sulfur Dioxide
# No filter
correlation(var_1 = blood_oxygen,
            var_2 = sulfur_window)
# One filter
correlation_one_filter(var_1 = blood_oxygen,
                       var_2 = sulfur_window,
                       filter_var_1 = sex,
                       filter_1 = "female")

## Heart Rate and Sulfur Dioxide
# Make new individual data with heart rate filters
# TO DO: We may want to just do this at the beginning of the analysis
ind_data_hr <- individual_data %>%
  filter(heart_rate > 30 & heart_rate < 200)
# No filter
correlation(ind_data = ind_data_hr,
            var_1 = heart_rate,
            var_2 = sulfur_window)
# One filter
correlation_one_filter(ind_data = ind_data_hr,
                       var_1 = heart_rate,
                       var_2 = sulfur_window,
                       filter_var_1 = sex,
                       filter_1 = "female")

## Heart Rate and Methane
# No filter
correlation(ind_data = ind_data_hr,
            var_1 = heart_rate,
            var_2 = methane)
# One filter
correlation_one_filter(ind_data = ind_data_hr,
                       var_1 = heart_rate,
                       var_2 = methane,
                       filter_var_1 = sex,
                       filter_1 = "female")
```
```{r multiple filter function, message=F, warning=F, include=F,echo=F}
# Alternative to coding in multiple filters is to ask the user to create filters. 
# Downside is it will be more interaction with actual code. 
# Upside is it can be done in only 2 steps.
# Steps:
# 1. New individual dataframe with filters
ind_data_filters <- individual_data %>%
  filter(sex == "male" & age > 50)
# 2. Call the correlation function
correlation(ind_data = ind_data_filters,
            var_1 = blood_oxygen,
            var_2 = sulfur_window)

# Multi filter function (not operational)
correlation_multi_filter <- function(ind_data = individual_data, air_data = air_quality, 
                            var_1, var_2, var_time = day, 
                            filters = ...,
                            types = ...,
                            conditions= ...) {
    var_1 <- enquo(var_1)
    var_2 <- enquo(var_2)
    var_time <- enquo(var_time)
    filters <- quos(filters)
    types <- quos(types)
    conditions <- quos(conditions)

    ind_data %>%
      filter(!!!filters !!!types !!!conditions) %>%
      bind_rows(air_data, .id = NULL) %>%
      mutate(id = as.factor(id)) %>%
      select(!!var_1, !!var_2, !!var_time) %>%
      filter(!is.na(!!var_1) | !is.na(!!var_2))%>%
      group_by(!!var_time) %>%
      summarize(mean_var1 = mean(!!var_1, na.rm=T),
                mean_var2 = mean(!!var_2, na.rm=T)) %>% 
      ungroup %>%
      filter(!is.na(mean_var1) & !is.na(mean_var2)) %>%
      select(mean_var1, mean_var2) %>% 
      boot::corr() %>% 
      print()
}
# The call (not operational)
correlation_fun(var_1 = heart_rate, 
                var_2 = methane,
                filters = list(sex, age),
                types = list("==", ">"),
                conditions = list("male", 50))
```

### Correlation plots
```{r plots, warning=F, message=F, echo=F}
# Create ggplot theme
theme_fair_tech <- theme(
  legend.position = "bottom",
  panel.background = element_rect(fill = NA),
  # panel.border = element_rect(fill = NA, color = "grey75"),
  axis.ticks = element_line(color = "grey95", size = 0.3),
  panel.grid.major = element_line(color = "grey95", size = 0.3),
  panel.grid.minor = element_line(color = "grey95", size = 0.3),
  legend.key = element_blank())

# Plot of Blood Oxygen and Sulfur Dioxide
individual_data %>%
  #filter(age > 50 & sex == "male") %>%
  bind_rows(air_quality, .id = NULL) %>%
  select(blood_oxygen, sulfur_window, day) %>%
  filter(!is.na(blood_oxygen) | !is.na(sulfur_window)) %>% 
  group_by(day) %>%
  summarize(mean_bo = mean(blood_oxygen, na.rm=T),
            mean_sd = mean(sulfur_window, na.rm=T)) %>% 
  ungroup %>%
  filter(!is.na(mean_bo) & !is.na(mean_sd)) %>%
  ggplot(aes(x= mean_sd, y= mean_bo)) + 
  geom_point() +
  geom_smooth(method = "lm", se=F) +
  theme_fair_tech + 
  xlab("Sulfur Dioxide") +
  ylab("Blood Oxygen") +
  ggtitle("Correlation between Blood Oxygen and Sulfur Dioxide",
    subtitle = "Fair Tech Collective"
    )
# Only 43 datapoints

# Plot of heart rate and Sulfur Dioxide
individual_data %>%
  filter(heart_rate > 30 & heart_rate < 200) %>%
  #filter(age > 50 & sex == "male") %>%
  bind_rows(air_quality, .id = NULL) %>%
  select(heart_rate, sulfur_window, day) %>%
  filter(!is.na(heart_rate) | !is.na(sulfur_window)) %>% 
  group_by(day) %>%
  summarize(mean_hr = mean(heart_rate, na.rm=T),
            mean_sd = mean(sulfur_window, na.rm=T)) %>% 
  ungroup %>%
  filter(!is.na(mean_hr) & !is.na(mean_sd)) %>%
  ggplot(aes(x= mean_sd, y= mean_hr)) + 
  geom_point()+
  geom_smooth(method = "lm", se=F) +
  theme_fair_tech + 
  xlab("Sulfur Dioxide") +
  ylab("Heart Rate") +
  ggtitle("Correlation between Heart Rate and Sulfur Dioxide",
    subtitle = "Fair Tech Collective"
    )

# Plot of heart rate and methane
individual_data %>%
  filter(heart_rate > 30 & heart_rate < 200) %>%
  #filter(age > 50 & sex == "male") %>%
  bind_rows(air_quality, .id = NULL) %>%
  select(heart_rate, methane, day) %>%
  filter(!is.na(heart_rate) | !is.na(methane)) %>% 
  group_by(day) %>%
  summarize(mean_hr = mean(heart_rate, na.rm=T),
            mean_m = mean(methane, na.rm=T)) %>% 
  ungroup %>%
  filter(!is.na(mean_hr) & !is.na(mean_m)) %>%
  ggplot(aes(x= mean_m, y= mean_hr)) + 
  geom_point()+
  geom_smooth(method = "lm", se=F) + 
  theme_fair_tech + 
  xlab("Methane") +
  ylab("Heart Rate") +
  ggtitle("Correlation between Heart Rate and Methane",
    subtitle = "Fair Tech Collective"
    )
```